apiVersion: v1
kind: Service
metadata:
  name: deepstream
  namespace: deepstream
spec:
  type: NodePort
  selector:
    app: deepstream
  ports:
  - name: rtsp
    protocol: TCP
    port: 8553
    nodePort: 30007
  - name: rtsp-out
    protocol: TCP
    port: 8554
    nodePort: 30008